from __future__ import annotations

from dataclasses import asdict, dataclass


@dataclass(frozen=True)
class ErrorCodeSpec:
    code: str
    title: str
    severity: str
    description: str
    remediation_hint: str
    repairability: str
    invariant_id: str | None = None

    def to_dict(self) -> dict[str, str]:
        data = asdict(self)
        return {key: value for key, value in data.items() if value is not None}


ERROR_CODES: dict[str, ErrorCodeSpec] = {
    "SCHEMA": ErrorCodeSpec(
        code="SCHEMA",
        title="Schema validation failed",
        severity="error",
        description="The evidence object does not satisfy the ASIEP JSON Schema.",
        remediation_hint="Repair the JSON object so it conforms to schemas/asiep.schema.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "SCHEMA_REQUIRED_FIELD": ErrorCodeSpec(
        code="SCHEMA_REQUIRED_FIELD",
        title="Required field missing",
        severity="error",
        description="A field required by the ASIEP schema is missing.",
        remediation_hint="Add the missing required field at the reported json_path.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "SCHEMA_TYPE_MISMATCH": ErrorCodeSpec(
        code="SCHEMA_TYPE_MISMATCH",
        title="Schema type mismatch",
        severity="error",
        description="A field has a value type that is not allowed by the ASIEP schema.",
        remediation_hint="Change the field value to the schema-required type.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "SCHEMA_CONST_MISMATCH": ErrorCodeSpec(
        code="SCHEMA_CONST_MISMATCH",
        title="Schema constant mismatch",
        severity="error",
        description="A field does not match a fixed value required by the ASIEP schema.",
        remediation_hint="Set the field to the constant value required by the schema.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "STATE_TRANSITION": ErrorCodeSpec(
        code="STATE_TRANSITION",
        title="Invalid lifecycle transition",
        severity="error",
        description="The lifecycle does not follow the ASIEP state machine.",
        remediation_hint="Reorder lifecycle events to follow DRAFT -> CANDIDATE -> EVALUATED -> GATED -> PROMOTED or REJECTED.",
        repairability="agent_fixable",
    ),
    "REF_UNRESOLVED": ErrorCodeSpec(
        code="REF_UNRESOLVED",
        title="Unresolved evidence reference",
        severity="error",
        description="A referenced evidence id is not present in the evidence array.",
        remediation_hint="Add the missing evidence object or update the reference to an existing evidence id.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "REF_DIGEST_FORMAT": ErrorCodeSpec(
        code="REF_DIGEST_FORMAT",
        title="Digest format invalid",
        severity="error",
        description="An evidence or external reference digest is not a sha256 64-character hex value.",
        remediation_hint="Set digest.algorithm to sha256 and digest.value to a 64-character hexadecimal SHA-256 digest.",
        repairability="external_evidence_required",
        invariant_id="I10",
    ),
    "DIGEST_BASIC": ErrorCodeSpec(
        code="DIGEST_BASIC",
        title="Digest format invalid",
        severity="error",
        description="Compatibility code for a basic digest format failure.",
        remediation_hint="Set digest.algorithm to sha256 and digest.value to a 64-character hexadecimal SHA-256 digest.",
        repairability="external_evidence_required",
        invariant_id="I10",
    ),
    "INV_MISSING_GATE_REPORT": ErrorCodeSpec(
        code="INV_MISSING_GATE_REPORT",
        title="Gate report missing",
        severity="error",
        description="A gate object is missing the evidence reference for its gate report.",
        remediation_hint="Add gates[].gate_report_ref pointing to gate_report evidence.",
        repairability="external_evidence_required",
        invariant_id="I5",
    ),
    "INV_SAFETY_REGRESSION": ErrorCodeSpec(
        code="INV_SAFETY_REGRESSION",
        title="Promotion blocked by safety regression",
        severity="error",
        description="The profile promotes an improvement while safety evidence records a regression or p2-or-higher failure.",
        remediation_hint="Do not promote when safety regression is true or a p2-or-higher safety check failed.",
        repairability="agent_fixable",
    ),
    "INV_FLIP_THRESHOLD": ErrorCodeSpec(
        code="INV_FLIP_THRESHOLD",
        title="Promotion blocked by flip threshold",
        severity="error",
        description="A flip-count metric exceeds the threshold while the gate decision promotes the improvement.",
        remediation_hint="Do not promote until flip_counts[].count is less than or equal to its threshold.",
        repairability="agent_fixable",
        invariant_id="I8",
    ),
    "INV_ROLLBACK_EVIDENCE": ErrorCodeSpec(
        code="INV_ROLLBACK_EVIDENCE",
        title="Rollback evidence missing",
        severity="error",
        description="A rollback state or rollback gate decision lacks rollback evidence.",
        remediation_hint="Add rollback.evidence_ref pointing to evidence with type rollback_report.",
        repairability="external_evidence_required",
        invariant_id="I9",
    ),
    "ROLLBACK_EVIDENCE": ErrorCodeSpec(
        code="ROLLBACK_EVIDENCE",
        title="Rollback evidence missing",
        severity="error",
        description="Compatibility code for missing rollback evidence.",
        remediation_hint="Add rollback.evidence_ref pointing to evidence with type rollback_report.",
        repairability="external_evidence_required",
        invariant_id="I9",
    ),
    "HASH_CHAIN_BROKEN": ErrorCodeSpec(
        code="HASH_CHAIN_BROKEN",
        title="Evidence hash chain broken",
        severity="error",
        description="An evidence link references a missing evidence object, breaking evidence-chain closure.",
        remediation_hint="Restore the referenced evidence object or update the evidence refs to close the chain.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "BUNDLE_SCHEMA": ErrorCodeSpec(
        code="BUNDLE_SCHEMA",
        title="Evidence bundle schema validation failed",
        severity="error",
        description="The local evidence bundle manifest does not satisfy the ASIEP evidence bundle schema.",
        remediation_hint="Repair bundle.json so it conforms to interfaces/asiep_evidence_bundle.schema.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "BUNDLE_ARTIFACT_MISSING": ErrorCodeSpec(
        code="BUNDLE_ARTIFACT_MISSING",
        title="Bundle artifact file missing",
        severity="error",
        description="A bundle artifact declared by URI and path is missing from the local bundle.",
        remediation_hint="Provide the real artifact file at the declared bundle-relative path or correct the artifact declaration.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "BUNDLE_DIGEST_MISMATCH": ErrorCodeSpec(
        code="BUNDLE_DIGEST_MISMATCH",
        title="Bundle artifact digest mismatch",
        severity="error",
        description="The artifact file exists, but its computed SHA-256 digest does not match the bundle declaration.",
        remediation_hint="Verify the evidence version; do not replace expected digest with actual digest unless an external review confirms the artifact is correct.",
        repairability="external_evidence_required",
        invariant_id="I10",
    ),
    "BUNDLE_MEDIA_TYPE_MISMATCH": ErrorCodeSpec(
        code="BUNDLE_MEDIA_TYPE_MISMATCH",
        title="Bundle artifact media type mismatch",
        severity="error",
        description="The artifact media type declaration is inconsistent with resolver expectations.",
        remediation_hint="Correct the media_type declaration or provide the artifact in the declared media type.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "BUNDLE_PATH_ESCAPE": ErrorCodeSpec(
        code="BUNDLE_PATH_ESCAPE",
        title="Bundle path escapes root",
        severity="error",
        description="A bundle-relative path attempts to resolve outside bundle_root.",
        remediation_hint="Reject this bundle path and require a safe path inside bundle_root.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "BUNDLE_RECORD_MISSING": ErrorCodeSpec(
        code="BUNDLE_RECORD_MISSING",
        title="Evidence record missing",
        severity="error",
        description="The bundle evidence_record_path does not resolve to a local ASIEP evidence record.",
        remediation_hint="Provide the real ASIEP evidence record at evidence_record_path or correct the bundle manifest.",
        repairability="external_evidence_required",
        invariant_id="I1",
    ),
    "BUNDLE_REF_UNDECLARED": ErrorCodeSpec(
        code="BUNDLE_REF_UNDECLARED",
        title="Evidence URI not declared in bundle",
        severity="error",
        description="The ASIEP evidence record references a URI that is not declared in bundle artifacts.",
        remediation_hint="Declare the real artifact in bundle artifacts or correct the evidence URI.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "BUNDLE_REF_UNUSED": ErrorCodeSpec(
        code="BUNDLE_REF_UNUSED",
        title="Bundle artifact unused by evidence record",
        severity="warning",
        description="The bundle declares an artifact URI that is not referenced by the ASIEP evidence record.",
        remediation_hint="Remove the unused artifact declaration if it is not needed by the evidence record.",
        repairability="auto_fixable",
        invariant_id="I4",
    ),
    "BUNDLE_MANIFEST_HASH_MISMATCH": ErrorCodeSpec(
        code="BUNDLE_MANIFEST_HASH_MISMATCH",
        title="Bundle manifest hash mismatch",
        severity="error",
        description="The computed canonical bundle manifest hash does not match integrity.bundle_manifest_hash.",
        remediation_hint="Review bundle.json changes and update the manifest hash only after confirming the manifest is correct.",
        repairability="human_required",
        invariant_id="I10",
    ),
    "IMPORT_SCHEMA": ErrorCodeSpec(
        code="IMPORT_SCHEMA",
        title="Import schema validation failed",
        severity="error",
        description="The import request or local source fixture does not match its M4 schema.",
        remediation_hint="Repair the request or fixture so it conforms to the relevant interface schema.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "IMPORT_SOURCE_UNSUPPORTED": ErrorCodeSpec(
        code="IMPORT_SOURCE_UNSUPPORTED",
        title="Import source unsupported",
        severity="error",
        description="The import request names a source_type that the ASIEP importer does not support.",
        remediation_hint="Use one of the supported_import_sources declared in profiles/asiep/v0.1/profile.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "IMPORT_SOURCE_MISSING": ErrorCodeSpec(
        code="IMPORT_SOURCE_MISSING",
        title="Import source missing",
        severity="error",
        description="The local trace fixture referenced by source_path is missing.",
        remediation_hint="Provide the local source fixture or correct source_path.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "IMPORT_REQUIRED_ROLE_MISSING": ErrorCodeSpec(
        code="IMPORT_REQUIRED_ROLE_MISSING",
        title="Required import role missing",
        severity="error",
        description="The local trace fixture does not include a role required by import_policy.",
        remediation_hint="Provide real source evidence for the missing role; do not fabricate gate reports, candidate diffs, feedback, or score artifacts.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "IMPORT_SENSITIVE_CONTENT_BLOCKED": ErrorCodeSpec(
        code="IMPORT_SENSITIVE_CONTENT_BLOCKED",
        title="Sensitive content blocked",
        severity="error",
        description="The fixture contains raw prompt, input, output, or message content blocked by the import policy.",
        remediation_hint="Remove raw sensitive content, replace it with external refs or redacted summaries, or explicitly use a test-only policy.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "IMPORT_MAPPING_INCOMPLETE": ErrorCodeSpec(
        code="IMPORT_MAPPING_INCOMPLETE",
        title="Import mapping incomplete",
        severity="error",
        description="The importer could not map source fields into the minimum ASIEP evidence bundle.",
        remediation_hint="Add source role markers or mapping metadata required by import_policy.json.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "IMPORT_ARTIFACT_WRITE_FAILED": ErrorCodeSpec(
        code="IMPORT_ARTIFACT_WRITE_FAILED",
        title="Artifact write failed",
        severity="error",
        description="The importer could not write an output artifact.",
        remediation_hint="Check output_bundle_dir permissions and rerun the local importer.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "IMPORT_BUNDLE_VALIDATION_FAILED": ErrorCodeSpec(
        code="IMPORT_BUNDLE_VALIDATION_FAILED",
        title="Generated bundle validation failed",
        severity="error",
        description="The generated bundle did not pass local resolver validation.",
        remediation_hint="Inspect resolver errors and regenerate the bundle without editing digests by hand.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "IMPORT_VALIDATOR_FAILED": ErrorCodeSpec(
        code="IMPORT_VALIDATOR_FAILED",
        title="Generated evidence validation failed",
        severity="error",
        description="The generated ASIEP evidence record did not pass validator checks.",
        remediation_hint="Inspect validator errors and repair source mapping or import policy.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "IMPORT_POLICY_VIOLATION": ErrorCodeSpec(
        code="IMPORT_POLICY_VIOLATION",
        title="Import policy violation",
        severity="error",
        description="The importer request or source would require a forbidden import action.",
        remediation_hint="Change the request or source fixture to comply with profiles/asiep/v0.1/import_policy.json.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PACKAGE_SCHEMA": ErrorCodeSpec(
        code="PACKAGE_SCHEMA",
        title="Package schema validation failed",
        severity="error",
        description="The package request or generated package document does not match its ASIEP M5 schema.",
        remediation_hint="Repair the package request or generated metadata so it conforms to the relevant package interface schema.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PACKAGE_INPUT_BUNDLE_MISSING": ErrorCodeSpec(
        code="PACKAGE_INPUT_BUNDLE_MISSING",
        title="Input bundle missing",
        severity="error",
        description="The package request points to a missing local input bundle manifest or bundle root.",
        remediation_hint="Provide the local ASIEP bundle or correct input_bundle_manifest_path and input_bundle_root.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "PACKAGE_RESOLVER_FAILED": ErrorCodeSpec(
        code="PACKAGE_RESOLVER_FAILED",
        title="Package resolver precondition failed",
        severity="error",
        description="The input ASIEP bundle did not pass local resolver checks before packaging.",
        remediation_hint="Resolve bundle errors before packaging; do not package an unvalidated evidence bundle.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "PACKAGE_VALIDATOR_FAILED": ErrorCodeSpec(
        code="PACKAGE_VALIDATOR_FAILED",
        title="Package validator precondition failed",
        severity="error",
        description="The input ASIEP evidence record did not pass validator checks before packaging.",
        remediation_hint="Repair the evidence object and rerun validator --bundle-root before packaging.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PACKAGE_POLICY_VIOLATION": ErrorCodeSpec(
        code="PACKAGE_POLICY_VIOLATION",
        title="Package policy violation",
        severity="error",
        description="The package request would require an action forbidden by package_policy.json.",
        remediation_hint="Change the package request to comply with profiles/asiep/v0.1/package_policy.json.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PACKAGE_ARTIFACT_COPY_FAILED": ErrorCodeSpec(
        code="PACKAGE_ARTIFACT_COPY_FAILED",
        title="Package artifact copy failed",
        severity="error",
        description="The packager could not copy a local bundle artifact into the package.",
        remediation_hint="Check local file permissions and ensure every source artifact remains inside the input bundle.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "PACKAGE_DIGEST_MISMATCH": ErrorCodeSpec(
        code="PACKAGE_DIGEST_MISMATCH",
        title="Package digest mismatch",
        severity="error",
        description="A copied package file digest does not match the source or manifest digest.",
        remediation_hint="Regenerate the package from a resolver-valid bundle; do not edit digests by hand.",
        repairability="external_evidence_required",
        invariant_id="I10",
    ),
    "PACKAGE_MANIFEST_INVALID": ErrorCodeSpec(
        code="PACKAGE_MANIFEST_INVALID",
        title="Package manifest invalid",
        severity="error",
        description="The generated package_manifest.json failed its ASIEP package manifest schema.",
        remediation_hint="Fix packager metadata generation so package_manifest.json conforms to the schema.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PACKAGE_FDO_RECORD_INVALID": ErrorCodeSpec(
        code="PACKAGE_FDO_RECORD_INVALID",
        title="FDO-like record invalid",
        severity="error",
        description="The generated local FDO-like record failed its schema.",
        remediation_hint="Fix fdo_record.json generation without claiming a global PID or registry registration.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PACKAGE_ROCRATE_INVALID": ErrorCodeSpec(
        code="PACKAGE_ROCRATE_INVALID",
        title="RO-Crate-like metadata invalid",
        severity="error",
        description="The generated RO-Crate-like metadata failed its schema.",
        remediation_hint="Fix ro-crate-metadata.json so agents can discover the package graph.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PACKAGE_PROV_INVALID": ErrorCodeSpec(
        code="PACKAGE_PROV_INVALID",
        title="PROV JSON-LD invalid",
        severity="error",
        description="The generated PROV JSON-LD failed its schema.",
        remediation_hint="Fix prov.jsonld so it expresses ASIEP activities, agents, entities, and package generation.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PACKAGE_WRITE_FAILED": ErrorCodeSpec(
        code="PACKAGE_WRITE_FAILED",
        title="Package write failed",
        severity="error",
        description="The packager could not write one or more package files.",
        remediation_hint="Check output_package_dir permissions and rerun the local packager.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "PACKAGE_PID_CLAIM_FORBIDDEN": ErrorCodeSpec(
        code="PACKAGE_PID_CLAIM_FORBIDDEN",
        title="Forbidden PID claim",
        severity="error",
        description="The package request or generated metadata attempted to claim a real global PID or registry submission.",
        remediation_hint="Use only local_pid values such as urn:asiep:fdo:<package_id>; do not claim global PID registration.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "EVAL_SCHEMA": ErrorCodeSpec(
        code="EVAL_SCHEMA",
        title="Evaluation schema validation failed",
        severity="error",
        description="The evaluation report, corpus manifest, or crosswalk matrix failed its ASIEP M6 schema.",
        remediation_hint="Repair the evaluation artifact so it conforms to the relevant M6 interface schema.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "EVAL_CORPUS_MISSING": ErrorCodeSpec(
        code="EVAL_CORPUS_MISSING",
        title="Evaluation corpus missing",
        severity="error",
        description="The evaluator could not find the machine-readable corpus manifest or a referenced corpus item.",
        remediation_hint="Provide the corpus manifest and referenced local examples before running evaluation.",
        repairability="external_evidence_required",
        invariant_id="I4",
    ),
    "EVAL_CROSSWALK_INCOMPLETE": ErrorCodeSpec(
        code="EVAL_CROSSWALK_INCOMPLETE",
        title="Crosswalk matrix incomplete",
        severity="error",
        description="The crosswalk matrix does not cover required field groups or invariants.",
        remediation_hint="Add mappings for every ASIEP core field group and ensure invariants I1-I10 are represented.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "EVAL_PIPELINE_STEP_FAILED": ErrorCodeSpec(
        code="EVAL_PIPELINE_STEP_FAILED",
        title="Evaluation pipeline step failed",
        severity="error",
        description="A validator, repairer, resolver, importer, or packager step failed unexpectedly during evaluation.",
        remediation_hint="Inspect the pipeline result and rerun the failed local command; do not fabricate success.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "EVAL_METRIC_COMPUTATION_FAILED": ErrorCodeSpec(
        code="EVAL_METRIC_COMPUTATION_FAILED",
        title="Metric computation failed",
        severity="error",
        description="The evaluator could not compute one of the declared M6 metrics.",
        remediation_hint="Check metric inputs, corpus coverage, and generated package availability.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "EVAL_REPORT_INVALID": ErrorCodeSpec(
        code="EVAL_REPORT_INVALID",
        title="Evaluation report invalid",
        severity="error",
        description="The generated ASIEP evaluation report failed its schema.",
        remediation_hint="Fix evaluator report generation so reports/asiep_v0.1_evaluation_report.json is schema-valid.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "EVAL_EXPECTED_RESULT_MISMATCH": ErrorCodeSpec(
        code="EVAL_EXPECTED_RESULT_MISMATCH",
        title="Expected result mismatch",
        severity="error",
        description="A corpus item produced a result that did not match expected_valid or expected_error_codes.",
        remediation_hint="Investigate the local tool output or update the corpus expectation only with evidence.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "EVAL_PAPER_ASSET_WRITE_FAILED": ErrorCodeSpec(
        code="EVAL_PAPER_ASSET_WRITE_FAILED",
        title="Paper asset write failed",
        severity="error",
        description="The evaluator could not write a paper-ready table, figure, or summary artifact.",
        remediation_hint="Check local reports/ and paper_assets/ write permissions and rerun evaluator.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "EVAL_POLICY_VIOLATION": ErrorCodeSpec(
        code="EVAL_POLICY_VIOLATION",
        title="Evaluation policy violation",
        severity="error",
        description="The evaluation would require an action forbidden by evaluation_policy.json.",
        remediation_hint="Keep evaluation local and do not use networks, external APIs, hidden failures, or fabricated success.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_POLICY_VIOLATION": ErrorCodeSpec(
        code="PAPER_POLICY_VIOLATION",
        title="Paper policy violation",
        severity="error",
        description="The paper draft, claim registry, or evidence map violates the ASIEP paper policy.",
        remediation_hint="Revise the paper artifact to follow profiles/asiep/v0.1/paper_policy.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PAPER_CLAIM_WITHOUT_EVIDENCE": ErrorCodeSpec(
        code="PAPER_CLAIM_WITHOUT_EVIDENCE",
        title="Paper claim lacks repository evidence",
        severity="error",
        description="A non-limitation paper claim has no local evidence_refs or artifact_refs.",
        remediation_hint="Attach repository evidence to the claim or weaken/remove the claim.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_EVALUATION_CLAIM_WITHOUT_METRIC": ErrorCodeSpec(
        code="PAPER_EVALUATION_CLAIM_WITHOUT_METRIC",
        title="Evaluation claim lacks metric reference",
        severity="error",
        description="A paper evaluation claim does not identify the M6 metric that supports it.",
        remediation_hint="Add metric_refs pointing to metric_results in reports/asiep_v0.1_evaluation_report.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PAPER_STRONG_CLAIM_UNDERSUPPORTED": ErrorCodeSpec(
        code="PAPER_STRONG_CLAIM_UNDERSUPPORTED",
        title="Strong paper claim undersupported",
        severity="error",
        description="A strong paper claim has fewer than two repository evidence references.",
        remediation_hint="Add another independent repository evidence reference or reduce claim_strength.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_FORBIDDEN_CLAIM": ErrorCodeSpec(
        code="PAPER_FORBIDDEN_CLAIM",
        title="Forbidden paper claim",
        severity="error",
        description="The paper draft contains a high-risk phrase that could overclaim external adoption, certification, production readiness, or benchmark status.",
        remediation_hint="Remove or rephrase the forbidden claim and state the local M0-M7 limitation explicitly.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_ORPHAN_CLAIM": ErrorCodeSpec(
        code="PAPER_ORPHAN_CLAIM",
        title="Orphan paper claim",
        severity="error",
        description="A claim is not connected to the paper evidence map or the evidence map references an unknown claim.",
        remediation_hint="Add the claim to manuscript/evidence_map.json or remove the stale claim reference.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PAPER_MISSING_SECTION": ErrorCodeSpec(
        code="PAPER_MISSING_SECTION",
        title="Required paper section missing",
        severity="error",
        description="The paper draft or evidence map does not include a required paper section.",
        remediation_hint="Add the required section to manuscript/paper_v0.1.md and map it in manuscript/evidence_map.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "PAPER_MISSING_TABLE": ErrorCodeSpec(
        code="PAPER_MISSING_TABLE",
        title="Required paper table missing",
        severity="error",
        description="A required paper-ready table is missing or not referenced by the evidence map.",
        remediation_hint="Generate or reference the required table under paper_assets/tables/.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_MISSING_FIGURE": ErrorCodeSpec(
        code="PAPER_MISSING_FIGURE",
        title="Required paper figure missing",
        severity="error",
        description="A required paper-ready figure is missing or not referenced by the evidence map.",
        remediation_hint="Generate or reference the required figure under paper_assets/figures/.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_EVIDENCE_REF_MISSING": ErrorCodeSpec(
        code="PAPER_EVIDENCE_REF_MISSING",
        title="Paper evidence reference missing",
        severity="error",
        description="A claim or evidence-map source references a repository path that does not exist.",
        remediation_hint="Correct the repository path or add the missing evidence artifact.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_ASSET_MISSING": ErrorCodeSpec(
        code="PAPER_ASSET_MISSING",
        title="Paper asset missing",
        severity="error",
        description="A required manuscript, table, figure, or paper-ready asset is missing.",
        remediation_hint="Create the required local paper asset or update the paper policy and evidence map consistently.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "PAPER_LINTER_FAILED": ErrorCodeSpec(
        code="PAPER_LINTER_FAILED",
        title="Paper linter failed",
        severity="error",
        description="The paper linter could not validate the claim registry or evidence map.",
        remediation_hint="Inspect the linter JSON output and repair the schema-invalid paper artifact.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "CITATION_SOURCE_REGISTRY_INVALID": ErrorCodeSpec(
        code="CITATION_SOURCE_REGISTRY_INVALID",
        title="Source registry invalid",
        severity="error",
        description="The external source registry failed schema or uniqueness checks.",
        remediation_hint="Repair references/source_registry.json so every source has stable unique ids, citation keys, and verification metadata.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "CITATION_CLAIM_MAP_INVALID": ErrorCodeSpec(
        code="CITATION_CLAIM_MAP_INVALID",
        title="Citation claim map invalid",
        severity="error",
        description="The claim-to-citation map failed schema or consistency checks.",
        remediation_hint="Repair references/citation_claim_map.json so every external claim maps to existing source ids and citation keys.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "CITATION_SOURCE_MISSING": ErrorCodeSpec(
        code="CITATION_SOURCE_MISSING",
        title="Citation source missing",
        severity="error",
        description="A citation map entry, paper draft, or bibliography references a missing source or citation key.",
        remediation_hint="Add the missing source to references/source_registry.json and BibTeX, or remove the unsupported citation reference.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "CITATION_UNVERIFIED_SOURCE_USED_AS_VERIFIED": ErrorCodeSpec(
        code="CITATION_UNVERIFIED_SOURCE_USED_AS_VERIFIED",
        title="Unverified source cited as ready",
        severity="error",
        description="A claim marked ready relies on a source whose verification_status is unverified.",
        remediation_hint="Verify the source and update its status with notes, or remove/downgrade the claim citation.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "CITATION_EXTERNAL_CLAIM_WITHOUT_SOURCE": ErrorCodeSpec(
        code="CITATION_EXTERNAL_CLAIM_WITHOUT_SOURCE",
        title="External claim lacks source",
        severity="error",
        description="A claim that requires external support has no citation key or source id.",
        remediation_hint="Attach a primary or canonical source, or weaken/remove the external claim.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "CITATION_UNSUPPORTED_CLAIM": ErrorCodeSpec(
        code="CITATION_UNSUPPORTED_CLAIM",
        title="Unsupported citation claim",
        severity="error",
        description="A citation claim map entry is explicitly marked unsupported.",
        remediation_hint="Remove the claim from paper_v0.2.md, downgrade it to a limitation, or add verified supporting sources.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "CITATION_SECONDARY_USED_WHEN_PRIMARY_AVAILABLE": ErrorCodeSpec(
        code="CITATION_SECONDARY_USED_WHEN_PRIMARY_AVAILABLE",
        title="Secondary source used when primary exists",
        severity="warning",
        description="A citation uses a secondary source where a primary or canonical source should be preferred.",
        remediation_hint="Prefer official standard documentation, regulations, product documentation, or primary papers when available.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "CITATION_BIBTEX_MISSING": ErrorCodeSpec(
        code="CITATION_BIBTEX_MISSING",
        title="BibTeX entry missing",
        severity="error",
        description="A citation key is present in the source registry or claim map but missing from references/asiep_references.bib.",
        remediation_hint="Add a BibTeX entry using the same stable citation_key; do not fabricate DOI or publication metadata.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "CITATION_FORBIDDEN_PRACTICE": ErrorCodeSpec(
        code="CITATION_FORBIDDEN_PRACTICE",
        title="Forbidden citation practice",
        severity="error",
        description="The citation layer or paper draft violates the machine-readable reference policy.",
        remediation_hint="Follow profiles/asiep/v0.1/reference_policy.json and remove overclaims, unverified source use, or unsupported standard claims.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "CITATION_LINTER_FAILED": ErrorCodeSpec(
        code="CITATION_LINTER_FAILED",
        title="Citation linter failed",
        severity="error",
        description="The citation linter could not validate citation infrastructure or encountered schema-invalid inputs.",
        remediation_hint="Inspect the citation linter JSON output and repair the referenced registry, map, BibTeX, or paper draft artifact.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "CITATION_REQUIRED_MARKER_REMAINS": ErrorCodeSpec(
        code="CITATION_REQUIRED_MARKER_REMAINS",
        title="Citation-required marker remains",
        severity="error",
        description="paper_v0.2.md still contains a citation_required marker.",
        remediation_hint="Replace citation_required with a verified citation key, or move the unverified claim to references/verification_gaps.md.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "VENUE_POLICY_INVALID": ErrorCodeSpec(
        code="VENUE_POLICY_INVALID",
        title="Venue policy invalid",
        severity="error",
        description="The venue policy failed schema validation or is missing required machine-readable fields.",
        remediation_hint="Repair the venue policy so it conforms to interfaces/asiep_venue_policy.schema.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "VENUE_PAPER_MISSING": ErrorCodeSpec(
        code="VENUE_PAPER_MISSING",
        title="Venue paper missing",
        severity="error",
        description="The venue linter could not find the target paper or brief.",
        remediation_hint="Create the target manuscript file or pass the correct --paper path.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "VENUE_REQUIRED_SECTION_MISSING": ErrorCodeSpec(
        code="VENUE_REQUIRED_SECTION_MISSING",
        title="Venue required section missing",
        severity="error",
        description="The venue-targeted paper is missing a section required by the venue policy.",
        remediation_hint="Add the missing section heading and keep it scoped to the target venue draft.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "VENUE_FORBIDDEN_CLAIM": ErrorCodeSpec(
        code="VENUE_FORBIDDEN_CLAIM",
        title="Forbidden venue claim",
        severity="error",
        description="The venue-targeted paper contains an overclaim forbidden by the venue policy.",
        remediation_hint="Remove the phrase or replace it with local-only, draft, or limitation language.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "VENUE_CITATION_GAP": ErrorCodeSpec(
        code="VENUE_CITATION_GAP",
        title="Venue citation gap",
        severity="error",
        description="The venue-targeted paper or claim map has an external claim without citation support.",
        remediation_hint="Add verified citation keys through references/citation_claim_map.json or remove the external claim.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "VENUE_EVIDENCE_GAP": ErrorCodeSpec(
        code="VENUE_EVIDENCE_GAP",
        title="Venue evidence gap",
        severity="error",
        description="A venue claim lacks repository evidence or references a missing artifact.",
        remediation_hint="Attach existing repository evidence or weaken the venue claim.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "VENUE_LIMITATION_MISSING": ErrorCodeSpec(
        code="VENUE_LIMITATION_MISSING",
        title="Venue limitation missing",
        severity="error",
        description="The venue-targeted paper does not preserve required local-only or minimal-implementation limitations.",
        remediation_hint="Add explicit local fixture, minimal implementation, and not external certification language.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "VENUE_AI_USE_DISCLOSURE_MISSING": ErrorCodeSpec(
        code="VENUE_AI_USE_DISCLOSURE_MISSING",
        title="AI-use disclosure missing",
        severity="error",
        description="The venue-targeted paper is missing a required AI-use disclosure draft.",
        remediation_hint="Add an AI-use disclosure section stating human final authoring and author responsibility.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "VENUE_AI_POLICY_RISK": ErrorCodeSpec(
        code="VENUE_AI_POLICY_RISK",
        title="AI policy risk",
        severity="warning",
        description="The venue policy creates a risk for AI-generated text or requires human final authoring.",
        remediation_hint="Treat Codex output as draft support only and require human rewrite, verification, and disclosure.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "VENUE_PAGE_BUDGET_RISK": ErrorCodeSpec(
        code="VENUE_PAGE_BUDGET_RISK",
        title="Venue page budget risk",
        severity="warning",
        description="The venue-targeted paper may exceed the venue page budget.",
        remediation_hint="Shorten prose, reduce tables or figures, or move material to appendix if allowed by the venue.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "VENUE_READINESS_REPORT_INVALID": ErrorCodeSpec(
        code="VENUE_READINESS_REPORT_INVALID",
        title="Venue readiness report invalid",
        severity="error",
        description="The generated venue readiness report failed its schema.",
        remediation_hint="Repair venue linter output so it conforms to interfaces/asiep_venue_readiness_report.schema.json.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "VENUE_LINTER_FAILED": ErrorCodeSpec(
        code="VENUE_LINTER_FAILED",
        title="Venue linter failed",
        severity="error",
        description="The venue linter could not complete readiness checks.",
        remediation_hint="Inspect the linter JSON output and repair the venue policy, paper draft, or required supporting artifacts.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "SUBMISSION_MANIFEST_INVALID": ErrorCodeSpec(
        code="SUBMISSION_MANIFEST_INVALID",
        title="Submission manifest invalid",
        severity="error",
        description="The M10 submission manifest failed schema validation.",
        remediation_hint="Repair submission/escience2026/submission_manifest.json so another agent can discover all M10 submission assets.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "SUBMISSION_HUMAN_PROTOCOL_INVALID": ErrorCodeSpec(
        code="SUBMISSION_HUMAN_PROTOCOL_INVALID",
        title="Human authoring protocol invalid",
        severity="error",
        description="The M10 human authoring protocol is missing or schema-invalid.",
        remediation_hint="Repair submission/escience2026/human_authoring_protocol.json and keep human_rewrite_required=true.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
    "SUBMISSION_MANUSCRIPT_MISSING": ErrorCodeSpec(
        code="SUBMISSION_MANUSCRIPT_MISSING",
        title="Submission manuscript missing",
        severity="error",
        description="A required M10 manuscript or submission package file is missing.",
        remediation_hint="Create the required file or correct its path in submission_manifest.json.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "SUBMISSION_AUTHOR_VERIFY_MARKERS_MISSING": ErrorCodeSpec(
        code="SUBMISSION_AUTHOR_VERIFY_MARKERS_MISSING",
        title="Author verification markers missing",
        severity="error",
        description="The M10 human-editable draft lacks AUTHOR_VERIFY markers for M11 human rewrite execution.",
        remediation_hint="Add AUTHOR_VERIFY markers to sections that require human rewriting, metric checking, citation checking, or CFP verification.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "SUBMISSION_LATEX_SCAFFOLD_MISSING": ErrorCodeSpec(
        code="SUBMISSION_LATEX_SCAFFOLD_MISSING",
        title="LaTeX scaffold missing",
        severity="error",
        description="The IEEE-style LaTeX scaffold is missing or lacks IEEE conference template cues.",
        remediation_hint="Create submission/escience2026/latex_scaffold/main.tex using IEEEtran conference 10pt structure.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "SUBMISSION_AI_DISCLOSURE_MISSING": ErrorCodeSpec(
        code="SUBMISSION_AI_DISCLOSURE_MISSING",
        title="Submission AI-use disclosure missing",
        severity="error",
        description="The eScience submission package lacks the required IEEE-style AI-use disclosure draft.",
        remediation_hint="Add acknowledgements disclosure text identifying the AI system, affected sections, level of use, and human author responsibility.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "SUBMISSION_ARTIFACT_STATEMENT_MISSING": ErrorCodeSpec(
        code="SUBMISSION_ARTIFACT_STATEMENT_MISSING",
        title="Artifact availability statement missing",
        severity="error",
        description="The M10 package lacks an artifact availability statement draft.",
        remediation_hint="Create submission/escience2026/artifact_availability_statement.md and mark repository/anonymization decisions for human review.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "SUBMISSION_DEADLINE_VERIFICATION_MISSING": ErrorCodeSpec(
        code="SUBMISSION_DEADLINE_VERIFICATION_MISSING",
        title="Deadline verification marker missing",
        severity="error",
        description="The eScience deadline ambiguity is not recorded as requiring human verification.",
        remediation_hint="Record the raw CFP deadline string and set requires_human_deadline_verification=true in venue_policy.json and submission_manifest.json.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "SUBMISSION_PAGE_BUDGET_RISK": ErrorCodeSpec(
        code="SUBMISSION_PAGE_BUDGET_RISK",
        title="Submission page budget risk",
        severity="warning",
        description="The human-editable draft or LaTeX scaffold may exceed the 8-page eScience budget.",
        remediation_hint="Use M11 human rewrite and LaTeX compilation to reduce the paper to 8 pages excluding references.",
        repairability="human_required",
        invariant_id="I4",
    ),
    "SUBMISSION_FINAL_CHECKLIST_MISSING": ErrorCodeSpec(
        code="SUBMISSION_FINAL_CHECKLIST_MISSING",
        title="Final human checklist missing",
        severity="error",
        description="The M10 package lacks the final human checklist required before M11 rewrite execution.",
        remediation_hint="Create submission/escience2026/final_human_checklist.md with CFP, rewrite, AI-use disclosure, and formatting checks.",
        repairability="agent_fixable",
        invariant_id="I4",
    ),
    "SUBMISSION_LINTER_FAILED": ErrorCodeSpec(
        code="SUBMISSION_LINTER_FAILED",
        title="Submission linter failed",
        severity="error",
        description="The submission linter detected an invalid M10 package or an internal linting inconsistency.",
        remediation_hint="Inspect the submission linter JSON output and repair the submission manifest, protocol, manuscript, or support files.",
        repairability="agent_fixable",
        invariant_id="I1",
    ),
}


def get_error_code(code: str) -> ErrorCodeSpec:
    return ERROR_CODES.get(
        code,
        ErrorCodeSpec(
            code=code,
            title="Unknown validation error",
            severity="error",
            description="The validator emitted an unregistered error code.",
            remediation_hint="Inspect the validator issue and register a stable remediation hint for this code.",
            repairability="human_required",
        ),
    )


def registry_as_dict() -> dict[str, dict[str, str]]:
    return {code: spec.to_dict() for code, spec in ERROR_CODES.items()}
